# POST http://localhost:3000/login HTTP/1.1
# content-type: application/json

# {
#     "username": "sure",
#     "password": "sure"
# }

# GET  http://localhost:3000/products HTTP/1.1


# GET  http://localhost:3000/logout HTTP/1.1